### ISSUE TITLE
Consider adding Billing Info

### ISSUE THREAD

**Issue by marcoby** [simon-r-watson/SophosCentral#1]
First, great module.  Thanks for the work you've done so far and making it public.

One suggestion would be to add a module for getting billing info.  My idea would be to use it to collect the info and automate documenting the licensing in IT Glue.  

It looks like you could use this as the endpoints:
    $month = (Get-Date).Month
    $year = (Get-Date).Year
    $uri = [System.Uri]::New("https://api.central.sophos.com/partner/v1/billing/usage/$month/$year")
    Invoke-SophosCentralWebRequest -Uri $uri -CustomHeader $header

I'm just starting out with modules so I didn't know how to add it to the module myself. 
https://developer.sophos.com/docs/partner-v1/1/routes/billing/usage/%7Byear%7D/%7Bmonth%7D/get

**Comment by simon-r-watson** [comment]
@marcoby I've added this to the repo for you to test. It doesn't work for me currently, as we don't use MSP Connect Flex (we resell 1 or 3 year)

- The function is Get-SophosCentralPartnerBilling
- When you download/clone the repo, use the psm1 to import the module (the psd1 may not import this function)

Example 1
`Get-sophosCentralPartnerBilling -LastMonth`

Example 2
`Get-SophosCentralPartnerBilling -Month 5 -Year 2022`

**Comment by marcoby** [comment]
Thanks.  I used it as an opportunity to learn so I forked the repo and ended up creating the exact same thing lol.

The only difference is was used parameters with a help message instead of a parameter set because hey I'm still learning.  Thanks again for your work.
