### ISSUE TITLE
Orgainization vs Partner

### ISSUE THREAD

**Issue by Chris-Smith-Dentons** [simon-r-watson/SophosCentral#3]
Nice work!

Needed to get some stuff working across multiple tenants in our orgainsation - but the organization APIs are a bit different - they used this:
https://api.central.sophos.com/organization/v1/tenants
instead of this:
https://api.central.sophos.com/partner/v1/tenants
And a differnet header:
X-Organization-ID 

I have managed to get it work but probably in a way that breaks code for partners. 

Also getting the tenants with >50 did not work - it was not returning response.pages.nextKey correctly - do you know about this.

Have impemented XDR queries - we used this lots.

Thanks

Chris

**Comment by simon-r-watson** [comment]
@Chris-Smith-Dentons I've added some initial support for enterprise tenants in this commit - https://github.com/simon-r-watson/SophosCentral/commit/d30d864363d4e6631454647c8625e70f517cb9d3. 

Could you test it out for me (I don't have access to an enterprise tenant to test with)? This change should automatically detect the creds as being enterprise, and should allow you to use 'Connect-SophosCentralCustomerTenant' and 'Get-SophosCentralCustomerTenant' as an Enterprise (and in turn the rest of the commands once connected).

For the listing more than 50 tenants, it looks like they are using a different way for pagination for that, I'll have a look at this a bit later

**Comment by simon-r-watson** [comment]
I've added their other pagination method in this commit https://github.com/simon-r-watson/SophosCentral/commit/0f79d8fe9b95c45cb573bd334037093194d494ac, could you see if you get all your tenants now?

**Comment by Chris-Smith-Dentons** [comment]
Your pagination code was similar to mine:

        $script:responsePagesTotal=$response.pages.total
        Write-Verbose "response.pages.total = $($response.pages.total)"
        if ($script:responsePagesTotal -gt 1) {
            do {
                if ($response.pages.current -lt $script:responsePagesTotal) {
                    $nextUri = $uri.AbsoluteUri -replace 'Total=true',"=$(($response.pages.current)+1)"
                    $response = Invoke-RestMethod -Uri $nextUri -Headers $header -UseBasicParsing
                    $response.items
                } else {
                    $finished = $true
                }
            } while ($finished -eq $false)
        } else {
            do {
                if ($response.pages.nextKey) {


Have dropped yours in and work great - thanks
