### ISSUE TITLE
Handling arrays as parameters

### ISSUE THREAD

**Issue by Chris-Smith-Dentons** [simon-r-watson/SophosCentral#5]
e.g Get-SophosCentralLiveDiscoverQuery -field ("name","description")

Can we add this to New-UriWithQuery at around line 20 - 
`            if ( $OriginalPsBoundParameters[$param] -is [array]) {
                $queryPart = $paraCaseSensitive + '=' + ($OriginalPsBoundParameters[$param] -join ",")
            } else {
                $queryPart = $paraCaseSensitive + '=' + $OriginalPsBoundParameters[$param]
            }`

Or am I missing something?

Thanks

**Comment by simon-r-watson** [comment]
Can do, does that change make it work for you? I haven't had a change to look at the Live Discovery api yet.

**Comment by Chris-Smith-Dentons** [comment]
I am mostly done with the live discovery stuff - can send over the code when am happy with it - it is working now and I am testing - mainly script kiddy your xdr stuff

had to add -depth 4 to this line:
       ` $bodyJson = $body | ConvertTo-Json -Depth 4`

in Invoke-SophosCentralWebRequest around line 80

**Comment by simon-r-watson** [comment]
Awesome, try sending it through as a Pull Request once your done

**Comment by Chris-Smith-Dentons** [comment]
Pull request sent - includes this fix, the Livediscovery stuff and a couple of changes to the XDR to tidy up parameters

**Comment by Chris-Smith-Dentons** [comment]
Arrays as parameter tested OK
