### ISSUE TITLE
Testing for connections using 

### ISSUE THREAD

**Issue by Chris-Smith-Dentons** [simon-r-watson/SophosCentral#7]
> Get-SophosCentralAlert

is thowing this:
Invoke-RestMethod: F:\githut\SophosCentral\SophosCentral\private\Invoke-SophosCentralWebRequest.ps1:52:17
Line |
  52 |      $response = Invoke-RestMethod @webRequest
     |                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {     "error": "forbidden",     "correlationId": "blah",     "requestId": blah",     "message": "Access is denied" }

[DBG]: PS C:\Users\dubadmin>

Possibly an issue with my API key - I am using -skipconnectiontest to get this to work but this is a change since an earlier release?

**Comment by simon-r-watson** [comment]
yeah, added a call to Get-SophosCentralAlert to check whether the enterprise/partner tenant has permissions to access the sub/customer tenant.

For the tenant where you get that error can you call any of the API's when connected to it? If so, I may need to look at a different API call to use for testing (might need to anyway, as getting the alerts is a bit slow)

**Comment by Chris-Smith-Dentons** [comment]
Yes – endpoints work but alerts do not.

Thanks

Chris

**Comment by simon-r-watson** [comment]
Interesting, was hoping to use on of these https://developer.sophos.com/docs/common-v1/1/overview so it works with tenants that don't have a form of endpoint (such as tenant that's Phish Threat/Email Advanced only). I'll change it around so the default isn't to test using alerts for the moment
