### ISSUE TITLE
Failing with JSON body

### ISSUE THREAD

**Issue by Chris-Smith-Dentons** [simon-r-watson/SophosCentral#8]
Invoke-SophosCentralWebRequest

line 48
   $Body.Add('ContentType', 'application/json')
Maybe should be
($WebRequest.Headers).Add('Content-Type', 'application/json')

**Comment by simon-r-watson** [comment]
Add, forgot to test the post's, etc after fixing delete. Mean't it to be

```
$webRequest.Add('ContentType', 'application/json')
```
